-- MySQL Script generated by MySQL Workbench
-- lun 24 sep 2018 07:02:37 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- sudo mysqldump -u usuarioruleta -p --no-create-info ruleta > /home/oquendo/Documents/backup.sql;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP DATABASE IF EXISTS `ruleta`;
CREATE DATABASE IF NOT EXISTS `ruleta`;
USE `ruleta`;
-- -----------------------------------------------------
-- Table `Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `id` INT NOT NULL,
  `billetera` DOUBLE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `Apuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `apuesta` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `usuario_id` INT NOT NULL,
  `monto` DOUBLE NULL,
  `cantidad_g` DOUBLE DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC),
  CONSTRAINT `usuario_id1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `HistorialBilletera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historial_billetera` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `usuario_id` INT NOT NULL,
  `ingreso` TINYINT(1) NULL,
  `cantidad` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `usuario_id_idx` (`usuario_id` ASC),
  CONSTRAINT `usuario_id2`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `HistorialApuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `historial_apuesta` (
  `id` INT AUTO_INCREMENT NOT NULL,
  `numero` INT NOT NULL,
  `color` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `Fichas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fichas` (
  `usuario_id` INT NOT NULL,
  `target` VARCHAR(200) NOT NULL,
  `value` INT NULL)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `Numero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `numero` (
  `num` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`num`))
ENGINE = InnoDB;

INSERT INTO `numero`(`num`, `cantidad`) VALUES
(0,0),(1,0),(2,0),(3,0),(4,0),(5,0),(6,0),(7,0),(8,0),(9,0),(10,0),
(11,0),(12,0),(13,0),(14,0),(15,0),(16,0),(17,0),(18,0),(19,0),(20,0),(21,0),
(22,0),(23,0),(24,0),(25,0),(26,0),(27,0),(28,0),(29,0),(30,0),(31,0),(32,0),
(33,0),(34,0),(35,0),(36,0),(37,0);

-- -----------------------------------------------------
-- Usuario
-- -----------------------------------------------------
CREATE USER IF NOT EXISTS 'usuarioruleta'@'localhost' IDENTIFIED BY 'eia2018*';
GRANT ALL PRIVILEGES ON `ruleta`.* TO 'usuarioruleta'@'localhost';
-- -----------------------------------------------------
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
